Algoritmo "AreaRetangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Altura de um Retangulo
// Descrição   : recebe os valores da base e da altura e calcula a área
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2024
Var
// Seção de Declarações das variáveis 
base, altura, area:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor da base:")
leia(base)
escreval("Digite o valor da altura:")
leia(altura)
area <- base * altura
escreval("A area deste retangulo é", area)
Fimalgoritmo